from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(463, 500)
        css_file = open('../Stylesheet/dialog_stylesheet.css').read()
        Dialog.setStyleSheet(css_file)
        self.clock_icon = QtWidgets.QLabel(Dialog)
        self.clock_icon.setGeometry(QtCore.QRect(30, 120, 30, 30))
        self.clock_icon.setText("")
        self.clock_icon.setPixmap(QtGui.QPixmap("../Assets/clock.png"))
        self.clock_icon.setScaledContents(True)
        self.clock_icon.setObjectName("clock_icon")
        self.location_icon = QtWidgets.QLabel(Dialog)
        self.location_icon.setGeometry(QtCore.QRect(30, 170, 30, 30))
        self.location_icon.setText("")
        self.location_icon.setPixmap(QtGui.QPixmap("../Assets/placeholder.png"))
        self.location_icon.setScaledContents(True)
        self.location_icon.setObjectName("location_icon")
        self.location = QtWidgets.QLineEdit(Dialog)
        self.location.setGeometry(QtCore.QRect(70, 210, 359, 28))
        self.location.setObjectName("location")
        self.from_dateEdit = QtWidgets.QDateEdit(Dialog)
        self.from_dateEdit.setGeometry(QtCore.QRect(30, 70, 110, 31))
        self.from_dateEdit.setAcceptDrops(False)
        self.from_dateEdit.setAutoFillBackground(False)
        self.from_dateEdit.setFrame(False)
        self.from_dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.from_dateEdit.setCalendarPopup(True)
        self.from_dateEdit.setObjectName("from_dateEdit")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(70, 265, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(150, 80, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.timeEdit = QtWidgets.QTimeEdit(Dialog)
        self.timeEdit.setGeometry(QtCore.QRect(130, 120, 61, 28))
        self.timeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.timeEdit.setObjectName("timeEdit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(70, 175, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_to_time = QtWidgets.QLabel(Dialog)
        self.label_to_time.setGeometry(QtCore.QRect(200, 125, 21, 16))
        self.to_timeEdit = QtWidgets.QTimeEdit(Dialog)
        self.to_timeEdit.setGeometry(QtCore.QRect(220, 120, 61, 28))
        self.to_timeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.to_timeEdit.setObjectName("to_timeEdit")
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setGeometry(QtCore.QRect(300, 120, 100, 28))
        self.radioButton.setChecked(False)
        self.radioButton.setObjectName("radioButton")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(30, 340, 401, 114))
        self.textEdit.setObjectName("textEdit")
        self.to_dateEdit = QtWidgets.QDateEdit(Dialog)
        self.to_dateEdit.setGeometry(QtCore.QRect(210, 70, 110, 31))
        self.to_dateEdit.setAcceptDrops(False)
        self.to_dateEdit.setAutoFillBackground(False)
        self.to_dateEdit.setFrame(False)
        self.to_dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.to_dateEdit.setCalendarPopup(True)
        self.to_dateEdit.setObjectName("to_dateEdit")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 310, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.save_btn = QtWidgets.QPushButton(Dialog)
        self.save_btn.setGeometry(QtCore.QRect(330, 20, 101, 30))
        self.save_btn.setObjectName("save_btn")
        self.noti_icon = QtWidgets.QLabel(Dialog)
        self.noti_icon.setGeometry(QtCore.QRect(30, 260, 30, 30))
        self.noti_icon.setText("")
        self.noti_icon.setPixmap(QtGui.QPixmap("../Assets/ring.png"))
        self.noti_icon.setScaledContents(True)
        self.noti_icon.setObjectName("noti_icon")
        self.title = QtWidgets.QLineEdit(Dialog)
        self.title.setGeometry(QtCore.QRect(30, 20, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(21)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(70, 125, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(190, 265, 161, 26))
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Dialog", None, -1))
        self.location.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "Add Location", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "Notifications", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "due to", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "Location", None, -1))
        self.radioButton.setText(QtWidgets.QApplication.translate("Dialog", "All day", None, -1))
        self.textEdit.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "Add Description", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "Descriptions", None, -1))
        self.label_to_time.setText(QtWidgets.QApplication.translate("Dialog", "-", None, -1))
        self.save_btn.setText(QtWidgets.QApplication.translate("Dialog", "CREATE", None, -1))
        self.title.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "Title", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "Time", None, -1))

